from sqlalchemy import Column, Integer, String, Text, Float, DateTime
from app.db_models.base import Base


class Defect(Base):
    __tablename__ = "defects"

    id = Column(Integer, primary_key=True, autoincrement=True)
    report_id = Column(String(128), unique=True, nullable=False)
    device_id = Column(String(64), nullable=False)
    device_serial = Column(String(255))
    device_type = Column(String(128))
    reported_by = Column(String(64), nullable=False)
    reported_by_name = Column(String(255))
    defect_type = Column(String(64), nullable=False)
    severity = Column(String(64), nullable=False)
    description = Column(Text, nullable=False)
    symptoms = Column(Text)
    report_target = Column(String(64), default="manager_admin")
    forwarded_to_management = Column(Integer, default=0)
    forwarded_to_management_at = Column(DateTime)
    forwarded_to_management_by = Column(String(64))
    forwarded_to_management_by_name = Column(String(255))
    operator_id = Column(String(64))
    sub_distributor_id = Column(String(64))
    status = Column(String(64), default="reported")
    resolution = Column(Text)
    resolved_by = Column(String(64))
    resolved_by_name = Column(String(255))
    resolved_at = Column(DateTime)
    replacement_requested_at = Column(DateTime)
    replacement_confirmed_at = Column(DateTime)
    replacement_confirmed_by = Column(String(64))
    replacement_confirmed_by_name = Column(String(255))
    return_amount = Column(Float, default=0)
    service_charge = Column(Float, default=0)
    payment_bill_url = Column(String(255))
    payment_confirmed = Column(Integer, default=0)
    payment_confirmed_at = Column(DateTime)
    payment_confirmed_by = Column(String(64))
    payment_confirmed_by_name = Column(String(255))
    payment_due_user_id = Column(String(64))
    payment_due_user_name = Column(String(255))
    images = Column(Text)
    auto_return_id = Column(String(64))
    replacement_device_id = Column(String(64))
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
