from sqlalchemy import Column, Integer, String, Text, DateTime, Numeric
from sqlalchemy import Boolean as SqlBool
from app.db_models.base import Base


class Defect(Base):
    __tablename__ = "defects"

    id = Column(Integer, primary_key=True, autoincrement=True)
    report_id = Column(String(128), unique=True, nullable=False)
    device_id = Column(String(64), nullable=False)
    device_serial = Column(String(255))
    device_type = Column(String(32))
    reported_by = Column(Integer, nullable=False)
    reported_by_name = Column(String(255))
    defect_type = Column(String(32), nullable=False)
    severity = Column(String(16), nullable=False)
    description = Column(String(1000), nullable=False)
    symptoms = Column(String(1000))
    report_target = Column(String(32), default="manager_admin")
    forwarded_to_management = Column(SqlBool, default=False)
    forwarded_to_management_at = Column(DateTime)
    forwarded_to_management_by = Column(Integer)
    forwarded_to_management_by_name = Column(String(255))
    operator_id = Column(Integer)
    sub_distributor_id = Column(Integer)
    status = Column(String(48), default="reported")
    resolution = Column(String(1000))
    resolved_by = Column(Integer)
    resolved_by_name = Column(String(255))
    resolved_at = Column(DateTime)
    replacement_requested_at = Column(DateTime)
    replacement_confirmed_at = Column(DateTime)
    replacement_confirmed_by = Column(Integer)
    replacement_confirmed_by_name = Column(String(255))
    return_amount = Column(Numeric(10, 2), default=0)
    service_charge = Column(Numeric(10, 2), default=0)
    payment_bill_url = Column(String(255))
    payment_confirmed = Column(SqlBool, default=False)
    payment_confirmed_at = Column(DateTime)
    payment_confirmed_by = Column(Integer)
    payment_confirmed_by_name = Column(String(255))
    payment_due_user_id = Column(Integer)
    payment_due_user_name = Column(String(255))
    images = Column(Text)
    auto_return_id = Column(String(64))
    replacement_device_id = Column(String(64))
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
