worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;
  server_tokens off;

  limit_req_zone $binary_remote_addr zone=api_rate:10m rate=10r/s;
  limit_req_zone $binary_remote_addr zone=site_rate:10m rate=30r/s;

  include /etc/nginx/conf.d/*.conf;
}
